name: Run E2E Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRESQL_USERNAME: admin
          POSTGRESQL_PASSWORD: 12345678
          POSTGRESQL_DATABASE: FindAFriendDatabase

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci

      - name: Reset Database
        run: npx prisma migrate reset --force --skip-seed
        env:
          DATABASE_URL: "postgresql://admin:12345678@localhost:5432/FindAFriendDatabase?schema=public"

      - run: npm run test:e2e
        env:
          JWT_SECRET: testing
          DATABASE_URL: "postgresql://admin:12345678@localhost:5432/FindAFriendDatabase?schema=public"